# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7ebLoudTH5dXszvJQ9OGU89fpl8Wtkf

## 1. Setup and Data Generation

First, let's import the necessary libraries and generate some synthetic web traffic data to work with. This data will include `timestamp`, `user_id`, `page_view`, and `session_duration`.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set random seed for reproducibility
np.random.seed(42)

# Generate synthetic data for web traffic
num_records = 1000
dates = pd.to_datetime(pd.date_range(start='2023-01-01', periods=num_records, freq='H'))
user_ids = np.random.choice(range(1, 201), num_records)
pages = ['/home', '/products', '/about', '/contact', '/blog', '/pricing']
page_views = np.random.choice(pages, num_records, p=[0.3, 0.25, 0.15, 0.1, 0.1, 0.1])
session_duration = np.random.normal(loc=120, scale=60, size=num_records).astype(int) # in seconds
session_duration[session_duration < 5] = 5 # Minimum session duration

df = pd.DataFrame({
    'timestamp': dates,
    'user_id': user_ids,
    'page_view': page_views,
    'session_duration_seconds': session_duration
})

display(df.head())
display(df.info())

"""## 2. Basic Data Exploration

Let's get a feel for the data by checking its distribution and summary statistics.
"""

print('Descriptive Statistics for Session Duration:')
display(df['session_duration_seconds'].describe())

print('\nUnique Users:', df['user_id'].nunique())

"""## 3. Key Metrics Calculation

Now, let's calculate some important web traffic metrics.
"""

# Total page views per page
page_view_counts = df['page_view'].value_counts().reset_index()
page_view_counts.columns = ['Page', 'Views']
print('Total Page Views per Page:')
display(page_view_counts)

# Average session duration
average_session_duration = df['session_duration_seconds'].mean()
print(f'\nAverage Session Duration: {average_session_duration:.2f} seconds')

# Daily page views
df['date'] = df['timestamp'].dt.date
daily_page_views = df.groupby('date').size().reset_index(name='Total_Page_Views')
print('\nDaily Page Views:')
display(daily_page_views.head())

"""## 4. Visualizing Web Traffic Trends

Visualizations help in understanding patterns and anomalies in the data.
"""

# Plot daily page views over time
plt.figure(figsize=(12, 6))
sns.lineplot(x='date', y='Total_Page_Views', data=daily_page_views)
plt.title('Daily Total Page Views Over Time')
plt.xlabel('Date')
plt.ylabel('Total Page Views')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot distribution of session durations
plt.figure(figsize=(10, 6))
sns.histplot(df['session_duration_seconds'], bins=30, kde=True)
plt.title('Distribution of Session Durations')
plt.xlabel('Session Duration (seconds)')
plt.ylabel('Frequency')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Plot top pages
plt.figure(figsize=(10, 6))
sns.barplot(x='Page', y='Views', data=page_view_counts)
plt.title('Most Popular Pages by Views')
plt.xlabel('Page')
plt.ylabel('Total Views')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## 5. User Journey Mapping (Conceptual)

Mapping user journeys often involves more complex sequence analysis, which typically requires a specific user flow dataset. Below is a conceptual idea of how you might start thinking about it, but generating a full journey requires more detailed path data.
"""

# Conceptual idea for a simplified user journey (requires more detailed data)
# For example, if you had data showing sequences of pages visited by each user.

# Let's simulate a 'path' for a few users based on page views
# In a real scenario, this would be derived from sequential user events.

# Group by user and timestamp to infer a simple path
user_paths = df.sort_values(['user_id', 'timestamp']).groupby('user_id')['page_view'].apply(lambda x: ' -> '.join(x.unique())).reset_index()

print('Example User Paths (simplified):')
display(user_paths.head())